language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.6
  - 7.1
  - 7.2
  - master

notifications:
  email: false

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
