language: php
dist: trusty
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.1
  - 7.2
  - master

notifications:
  email: false

env:
  - PREFER_LOWEST=--prefer-lowest
  - PREFER_LOWEST=

matrix:
  include:
    - php: 5.3
      dist: precise

  exclude:
    - php: 7.2
      env: PREFER_LOWEST=--prefer-lowest

    - php: master
      env: PREFER_LOWEST=--prefer-lowest

install:
  - composer update ${PREFER_LOWEST}

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
