language: php
dist: trusty
sudo: false

php:
  - 5.4
  - 5.6
  - 7.1
  - 7.2
  - master

notifications:
  email: false

matrix:
  include:
    - php: 5.3
      dist: precise

install:
  - composer update --prefer-lowest

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
